---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns-aws-client
spec:
  schedule: "* */12 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ddns-aws-client
              image: rogelioo/ddns-aws-client:latest
              args:
                - --api-key
                - $API_KEY
                - --url
                - <API_URL>
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secret-ddns-aws-client
                      key: key
          restartPolicy: OnFailure
