service: lambda
app: ddns-aws-lambda

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "route53:ChangeResourceRecordSets"
      Resource: arn:aws:route53:::hostedzone/${env:HOSTED_ZONE_ID}
  apiKeys:
    - client

functions:
  ddns:
    handler: src/handler.handle
    environment:
      HOSTED_ZONE_ID: ${env:HOSTED_ZONE_ID}
      RECORD_NAME: ${env:RECORD_NAME}
    events:
      - http:
          path: ""
          method: POST
          private: true
